### ISSUE TITLE
There is no requirements.txt file in repository

### ISSUE THREAD

**Issue by JovanBosic** [xuarehere/yolovx_deepsort_pytorch#1]
There is no requirements.txt file in repository.

Can you please explain more about mmdetection and why we are using it. I need to use deep sort with yolox, yolor, yolov6 and yolov7. Currently I am struggling with installing mmcv-full.

**Comment by SaiAswath27** [comment]
install deep_sort requirements.txt for starters then mmcv-full 

https://github.com/ZQPei/deep_sort_pytorch/blob/master/requirements.txt
