### ISSUE TITLE
I want to use the yolov7, do I need to take the step2 to download yolov3's parameters?

### ISSUE THREAD

**Issue by RonaldYuren** [xuarehere/yolovx_deepsort_pytorch#6]
I want to use the yolov7, do I need to take the step2 to download yolov3's parameters?

if not, what step I should take in step2?

**Comment by thisimyusername** [comment]
you need a yolov7 model, and modify model path in /config/yolov7.yaml, then run "# yolov7 + deepsort on video
python3 deepsort.py ./001.avi --save_path ./output/yolov7/001 --config_detection ./configs/yolov7.yaml --detect_model yolov7", make sure you have a video like 001.avi and path is right.

**Comment by xuarehere** [comment]
> you

first,
please download yolov7.pt to your project.
For example:
```
wget https://github.com/WongKinYiu/yolov7/releases/download/v0.1/yolov7.pt
```

then
modify your config
```
vi configs/yolov7.yaml
```

and run,
```
python deepsort.py --detect_model yolov7     --config_detection ./configs/yolov7.yaml   ./001.avi --save_path ./output/yolov7/001/

```

**Comment by xuarehere** [comment]
@RonaldYuren 

first,
please download yolov7.pt to your project.
For example:
```
wget https://github.com/WongKinYiu/yolov7/releases/download/v0.1/yolov7.pt
```

then
modify your config
```
vi configs/yolov7.yaml
```

and run,
```
python deepsort.py --detect_model yolov7     --config_detection ./configs/yolov7.yaml   ./001.avi --save_path ./output/yolov7/001/

```
