### ISSUE TITLE
I trained yolov5 model but result is different with this repo in inference.

### ISSUE THREAD

**Issue by thisimyusername** [xuarehere/yolovx_deepsort_pytorch#7]
I trained yolov5 model with code from "https://github.com/ultralytics/yolov5", and then i use the trained model in this repo for track. 
First, inference result with  "https://github.com/ultralytics/yolov5" is:
![image](https://user-images.githubusercontent.com/38216798/183555895-fedeff66-df7e-4232-a5ea-b41146ec33ef.png)
However, when put the same model in this repo, result mAP:0.5:0.95 is different, 
![image](https://user-images.githubusercontent.com/38216798/183556123-71cb5f79-8e72-4cb6-98c8-c41f56a56341.png)
(I saved boxes result to .json by myself, and use coco-eval get above table.)
does any suggestions?Thanks!

**Comment by xuarehere** [comment]
Please take the official one, the project takes v4.0  version

**Comment by xuarehere** [comment]
I have update YOLOv5 to the latest version(v6.2), please you update the project.

> Please take the official one, the project takes v4.0 version



> Please take the official one, the project takes v4.0 version

I have update YOLOv5 to the latest version(v6.2), please you update the project.
