### ISSUE TITLE
Update detectors/YOLOV5 - compabality issues

### ISSUE THREAD

**Issue by Wincioor11** [xuarehere/yolovx_deepsort_pytorch#8]
Can you update the YOLOv5 to the latest version? I don't know which one you used but I guess its 4.0 or 5.0 as there are compatibility issues like:
RuntimeError: The size of tensor a (80) must match the size of tensor b (48) at non-singleton dimension 3 when trying to use the weights from the v6.2 release.

**Comment by xuarehere** [comment]
The YOLOv5 takes v4.0 version, 

Thanks for your report. I will update the YOLOv5 to the latest versionthe next update.
